### ISSUE TITLE
Luna build fails.

### ISSUE THREAD

**Issue by samielhini** [DEGoodmanWilson/luna#47]
Hello there,

It seems that libmagic/5.29@DEGoodmanWilson/testing is not resolving in neither your remote or the other conan remotes.  I was able to build separately and install in my own cache.

Also self.requires.add("nl-json/2.1.1@genvidtech/1.4.0", private=False) does not resolve anymore.  I replaced it with self.requires.add("jsonformoderncpp/2.1.1@vthiery/stable", private=False) on my filesystem and the first build step seems to succeed.

**Comment by DEGoodmanWilson** [comment]
At the moment, the only branch that even has a chance at building is stable/5.0.0. That branch has those changes already ;)
