### ISSUE TITLE
Conan Build Fails

### ISSUE THREAD

**Issue by samielhini** [DEGoodmanWilson/luna#48]
For some reason on Linux CMakeLists.txt requires this:

target_link_libraries(luna ${CONAN_LIBS} -pthread). 

Without it linking fails with undefined symblosl for the thread library.

**Comment by DEGoodmanWilson** [comment]
Ah yes, that is because libmicrohttpd relies on pthreads. However, the libmicrohttpd package _should_ be exporting that as a required library. Which it is not! Can you re-open this same issue here:
https://github.com/DEGoodmanWilson/conan-libmicrohttpd
being the real source of the problem? 🙇
