### ISSUE TITLE
conan failing

### ISSUE THREAD

**Issue by jdamme** [DEGoodmanWilson/luna#51]
I have never used conan so troubleshooting errors is a bit difficult.

$ conan --version
Conan version 1.1.1

$conan remote add bincrafters -i 0 https://api.bintray.com/conan/bincrafters/public-conan
$conan remote add DEGoodmanWilson -i 0 https://api.bintray.com/conan/degoodmanwilson/opensource

$ conan install -o build_luna_examples=True --build=missing
usage: conan install [-h] [-g GENERATOR] [-if INSTALL_FOLDER] [-m [MANIFESTS]]
                     [-mi [MANIFESTS_INTERACTIVE]] [-v [VERIFY]]
                     [--no-imports] [-u] [-pr PROFILE] [-r REMOTE]
                     [-o OPTIONS] [-s SETTINGS] [-e ENV]
                     [-b [BUILD [BUILD ...]]]
                     path
conan install: error: too few arguments
ERROR: Exiting with code: 2

$ conan install .
Version range '~=1.2' required by 'gnutls/3.6.2@DEGoodmanWilson/stable' resolved to 'zlib/1.2.11@conan/stable'
libmagic/5.29@DEGoodmanWilson/testing: Not found in local cache, looking in remotes...
libmagic/5.29@DEGoodmanWilson/testing: Trying with 'DEGoodmanWilson'...
libmagic/5.29@DEGoodmanWilson/testing: Trying with 'bincrafters'...
libmagic/5.29@DEGoodmanWilson/testing: Trying with 'conan-center'...
ERROR: Unable to find 'libmagic/5.29@DEGoodmanWilson/testing' in remotes

**Comment by DEGoodmanWilson** [comment]
Howdy! I'm sorry to say that for a range of reasons, the current stable version of Luna does not build, at all. This is a known issue, and is the result of changes in various dependencies as you can see. I'm really sorry!

You can help us test the newest beta branch, however. There are some problems getting it to build too, unfortunately, but help is certainly welcome. Look at `luna/5.0.0@DEGoodmanWilson/testing`, if you don't mind?
