### ISSUE TITLE
C++ newbie here!  Trying to get luna working

### ISSUE THREAD

**Issue by brendanAlbert** [DEGoodmanWilson/luna#67]
Salutations!

C++ beginner here.
I am trying to get luna up and running but I can't seem to figure out what to do.
My apologies if this is referenced somewhere and I missed it.

From the luna/examples directory I have tried compiling "g++ basic_webapp.cpp -o app", but I get the error "luna/luna.h" not found.
Here is a picture:
<img width="496" alt="luna_error" src="https://user-images.githubusercontent.com/17652687/46776495-b65aef00-ccc0-11e8-9d74-f50743fa2a68.png">

Is this because I was supposed to run a makefile using cmake?
I also noticed conan is referenced, which I am also unfamiliar with ☹️ 

Any help would be most appreciated,  thank you!!

**Comment by DEGoodmanWilson** [comment]
Howdy! There are written instructions for getting started, but it seems you had some difficulty finding them. That tells me I have some work to do to make them more discoverable—my sincerest apologies!

Anyway, never fear, the instructions are here:
https://luna.goodman-wilson.com/using.html

GIve them a go, see if you can make them work, and please do feel free to share your feedback here!

Indeed, if you are participating in [Hacktoberfest](https://hacktoberfest.digitalocean.com/), helping me update the docs to make them easier to find and easier to use is a great opportunity to create an impactful pull request!

**Comment by brendanAlbert** [comment]
Thank you @DEGoodmanWilson for the link!
I think it was user error (me) who is to blame for missing the instructions.

Everything seemed to go swimming until the conan install step.  
But I noticed in a recent issue you said that conan is down at the moment.

I look forward to getting luna up and running when conan comes back up!

Thank you for the suggestion regarding updating the docs for Hacktoberfest.
I will see what I can do to improve them; they are already pretty spiffy! 👍

**Comment by brendanAlbert** [comment]
Great success!
I do have one comment, which perhaps I will add to the docs with your blessing.
After running `conan build .`

I got this error:
<img width="1056" alt="conan_build_error" src="https://user-images.githubusercontent.com/17652687/46828696-a985dc00-cd50-11e8-8369-986cc580f06a.png">

The "sh: cmake command not found" reveals the problem.  cmake was not installed!
To fix it, I ran `brew install cmake`.  The build command ran perfectly after that.

I would love to help with the docs by adding such a troubleshooting tip.

**Comment by DEGoodmanWilson** [comment]
I'm glad you were able to build it! TRoubleshooting steps are especially welcome, as are any steps that I missed (did I fail to mention installing cmake?). Also please feel free to suggest reorganizations to the documents that make finding these instructions easier!

I also noticed that there isn't good or timely documentation on using the project template as a way to get started quickly.

I have a new branch called `docs-improvement-project` that you could use as a basis for a fork.

**Comment by DEGoodmanWilson** [comment]
On that note, I'm going to close this issue as resolved, but feel free to continue communicating here. I am looking forward to any PRs you offer!
