### ISSUE TITLE
Unable to build the project using Conan.

### ISSUE THREAD

**Issue by abhaysibal** [DEGoodmanWilson/luna#69]
Hi there,

I am trying to build the Luna project by following the instructions on https://github.com/DEGoodmanWilson/luna/blob/stable/5.0.4/docs/using.md

I am not able to build the project but rather I am running into the error 
![image](https://user-images.githubusercontent.com/7008352/46810611-ac9fbd00-cd8e-11e8-9174-c986952453e9.png)
when I try to build using the command : 
`sudo conan install . -o build_luna_examples=True -s compiler.libcxx=libstdc++11`

Please let me know how do I fix this?

Thanks!

**Comment by DEGoodmanWilson** [comment]
At the moment, Conan appears to be down… 🤦‍♂️  Not your fault!

**Comment by abhaysibal** [comment]
Hi @DEGoodmanWilson  Is there a place where we can see the current functional status of Conan?

Also, can we build the code without using conan? I am interested in learning about the project and would love to have a running build up.

**Comment by DEGoodmanWilson** [comment]
Conan seems to be working now. The poster in #67 is reporting success, so I am going to close this issue as resolved. Please do feel free to continue commenting on this issue to stay in touch, or reopen it if you encounter further difficulties!
